### ISSUE TITLE
Rack-in-a-Box 1.9 testing

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#140]
Building upon the previous template.

### Using Virtualbox

 - [x] Homepage at localhost:80 is up
 - [x] SPARQLGraph at localhost:80/sparqlGraph is up
 - [x] Swagger at localhost:12058 is up

### Using Hyper-V

 - [] Homepage at localhost:80 is up
 - [] SPARQLGraph at localhost:80/sparqlGraph is up
 - [] Swagger at localhost:12058 is up

### Documentation

 - [x] User guide link points to the current version
 - [x] Documentation is up-to-date (#98)
 - [x] Documentation is coherent (#96, #97)
 - [x] RiB Docker instructions reference the correct version (#95)

### SPARQLGraph

 - [x] Able to run nodegroup queries from SPARQLGraph with reasonable results
 - [x] SPARQLGraph "Check services" reports everything is up
 - [x] Demo content works
 - [x] No Javascript alerts!

Nothing seems alarming:
![image](https://user-images.githubusercontent.com/478606/91351261-4b4d2f80-e7e8-11ea-9af7-f686dbe9e068.png)

### rack cli

I ran `BASE_URL=http://192.168.0.36 ./setup-rack.sh` and it worked successfully all the way.
