### ISSUE TITLE
Rack-in-a-Box v0.9 test results

### ISSUE THREAD

**Issue by langston-barrett** [ge-high-assurance/RACK#94]
Here are the results of my tests. I've tried to make a checklist so testing is easier next time. I'll make issues for each of the incomplete items and we can go from there.

 - [x] Homepage at localhost:80 is up
 - [x] SPARQLGraph at localhost:80/sparqlGraph is up
 - [x] Swagger at localhost:12058 is up

Inspected manually and with this script:
```bash
curl -q -L -I localhost:80
curl -q -L -I localhost:80/sparqlGraph
curl -q -L -I localhost:12058/swagger-ui.html
```

 - [ ] Docker logs contain no errors: `docker logs $(docker ps -q) | grep -i error`
```
sparqlGraphResultsService.service: 2020-07-29 21:12:16 Error reading json datafile from metaFile: /tmp/DISPATCH_RESULTS/results_85648fdb-e978-4a6d-9e50-ffa0545db4c2_metadata.json
sparqlGraphResultsService.service: 2020-07-29 21:12:16 Error reading json datafile from metaFile: /tmp/DISPATCH_RESULTS/results_afe92041-a5e5-49fc-8bbf-ecbc7a33956b_metadata.json
sparqlGraphResultsService.service: 2020-07-29 21:12:16 Error reading json datafile from metaFile: /tmp/DISPATCH_RESULTS/results_197f110a-bdf7-405e-96e4-eada914a0982_metadata.json
sparqlGraphResultsService.service: 2020-07-29 21:12:16 Error reading json datafile from metaFile: /tmp/DISPATCH_RESULTS/results_req_408484cd-829f-424a-94aa-a0999486f338_metadata.json
```
All these tests were run against the v0.9 release with image ID `2abf47f27b30`. 

### Documentation

 - [x] User guide link points to the current version

This link points to v0.1. Looks like it's current on the wiki, so presumably this is already fixed for the final release.

 - [x] Documentation is up-to-date (#98)

Turnstile demo includes the phrase

> click on any entry that starts with "TA3"

which is out of date with current names.

 - [x] Documentation is coherent (#96, #97)

I believe we said we weren't going to include the cookbook, but it looks like
it's in there.

Also the "RACK Predefined Queries" section needs context. Are these in RiB right
now? Upcoming? How are they used?

 - [x] RiB Docker instructions reference the correct version (#95)

They reference v0.1.

### SPARQLGraph

 - [x] Able to run nodegroup queries from SPARQLGraph with reasonable results
 - [x] SPARQLGraph "Check services" reports everything is up
 - [x] Demo content works
 - [ ] No Javascript alerts!

I get the following alert in qutebrowser, but not with Firefox.
```
From http://localhost/:
Error: Uncaught Error: Can't decode OntologyInfo JSON with newer version > 2 found: 3 url: http://localhost/sparqlGraph/js/ontologyinfo.js line: 1314 undefined column: 13 error: Error: Can't decode OntologyInfo JSON with newer version > 2 found: 3
```

### rack.py

The following script exercises most rack.py functionality:
```bash
#!/usr/bin/env bash

set -ex

cd rack
git fetch --all
git reset --hard origin/master

cd RACK-Ontology/scripts
rm -rf venv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
dir=$(mktemp -d)
./rack.py plumbing retrieve-nodegroups '.*' "${dir}"
for nodegroup in "${dir}"/ingest*.json; do
  base=$(basename "${nodegroup}")
  grp=${base%.json}
  ./rack.py data export "${grp}" http://rack001/data
done

./rack.py data import ../models/TurnstileSystem/Data/import.yaml
./rack.py plumbing store-nodegroups ../../nodegroups/ingestion
./rack.py data import ../models/TurnstileSystem/Data/import.yaml
```
It works fine.
